const constatnts = {
    ERROR: 'ERROR',
    POPULATE_MOVIES: 'POPULATE_MOVIES',
    ITEM_SELECTED: 'ITEM_SELECTED',
    SET_SEARCH_BY: 'SET_SEARCH_BY',
    SET_FILTER_BY: 'SET_FILTER_BY',
    SET_ACTIVE_FILTER: 'SET_ACTIVE_FILTER',
}

export default constatnts;
