const constatnts = {
    ERROR: 'ERROR',
    POPULATE_MOVIES: 'POPULATE_MOVIES',
    ITEM_SELECTED: 'ITEM_SELECTED',
    SET_SEARCH_BY: 'SET_SEARCH_BY',
    SET_FILTER_BY: 'SET_FILTER_BY',
    SET_ACTIVE_FILTER: 'SET_ACTIVE_FILTER',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    GET_MOVIE_DETAILS: 'GET_MOVIE_DETAILS',
    PUT_MOVIE_TO_CACHE: 'PUT_MOVIE_TO_CACHE',
    GET_MOVIES_FROM_LOCALSTORAGE: 'GET_MOVIES_FROM_LOCALSTORAGE',
}

export default constatnts;
